/**
 * CAPITAL AI — ENTERPRISE MARKET INTELLIGENCE ARCHITECTURE
 * CANONICAL ANALYSIS COMPONENT REGISTRY (PART 1 OF 3)
 *
 * Implements the 50 Enterprise Analysis & Scoring Components with explicit
 * domain boundaries, contract-first interfaces, validation policies, and
 * clear separation between verified provider facts, derived features, and model inferences.
 */

import { z } from 'zod';
import { AssetClassSchema, AssetClass } from './common';

// =============================================================================
// DOMAIN TAXONOMY & STATUS ENUMS
// =============================================================================

export const CanonicalDomainSchema = z.enum([
  'market-data',
  'provider-registry',
  'asset-master',
  'feature-store',
  'market-intelligence',
  'scoring',
  'ranking',
  'evidence',
  'data-quality',
  'risk-controls',
  'pipeline-configurator',
  'observability',
  'ui-explainability',
]);
export type CanonicalDomain = z.infer<typeof CanonicalDomainSchema>;

export const ComponentLifecycleStatusSchema = z.enum([
  'planned',
  'mock',
  'shadow',
  'active',
  'degraded',
  'blocked',
  'retired',
]);
export type ComponentLifecycleStatus = z.infer<typeof ComponentLifecycleStatusSchema>;

export const DataProvenanceModeSchema = z.enum([
  'live',
  'delayed',
  'cached',
  'simulated',
  'unavailable',
  'degraded',
]);
export type DataProvenanceMode = z.infer<typeof DataProvenanceModeSchema>;

export const RefreshFrequencySchema = z.enum([
  'tick_realtime',
  'sub_second_conflated',
  'one_minute',
  'five_minutes',
  'hourly',
  'daily_eod',
  'on_event',
]);
export type RefreshFrequency = z.infer<typeof RefreshFrequencySchema>;

// =============================================================================
// COMPONENT REGISTRY ENTRY SCHEMA
// =============================================================================

export const AnalysisComponentRegistryEntrySchema = z.object({
  componentId: z.string().min(1),
  displayName: z.string().min(1),
  domain: CanonicalDomainSchema,
  assetClassScope: z.array(z.string()).min(1),
  status: ComponentLifecycleStatusSchema,
  provenanceMode: DataProvenanceModeSchema,
  inputContracts: z.array(z.string()).min(1),
  outputContract: z.string().min(1),
  featureDependencies: z.array(z.string()),
  providerDependencies: z.array(z.string()),
  calculationVersion: z.string().regex(/^\d+\.\d+\.\d+$/),
  refreshPolicy: z.object({
    frequency: RefreshFrequencySchema,
    maxStalenessSeconds: z.number().positive(),
    timeoutMs: z.number().positive(),
  }),
  weightPolicy: z.object({
    defaultWeight: z.number().min(0).max(1),
    isEligibleGate: z.boolean(),
    isVetoOverride: z.boolean(),
  }),
  confidencePolicy: z.object({
    minimumDataSufficiencyRatio: z.number().min(0).max(1),
    confidenceDecayHalfLifeHours: z.number().positive(),
  }),
  riskPolicy: z.object({
    penaltyCeiling: z.number().min(0).max(100),
    blocksActionableRank: z.boolean(),
  }),
  reasonCodeCatalog: z.array(
    z.object({
      code: z.string(),
      descriptionDe: z.string(),
      severity: z.enum(['info', 'warning', 'critical']),
    })
  ),
  owner: z.string(),
  lastValidatedAt: z.string(),
});
export type AnalysisComponentRegistryEntry = z.infer<typeof AnalysisComponentRegistryEntrySchema>;

// =============================================================================
// CANONICAL 50 COMPONENT DEFINITIONS
// =============================================================================

export const CANONICAL_50_COMPONENTS: AnalysisComponentRegistryEntry[] = [
  // 1-5: Integrity, Quality & Eligibility Gates
  {
    componentId: 'market_integrity_gate',
    displayName: 'Market Integrity Gate',
    domain: 'data-quality',
    assetClassScope: ['crypto', 'equity_us', 'equity_eu', 'commodities', 'forex', 'indices', 'futures', 'bonds'],
    status: 'active',
    provenanceMode: 'live',
    inputContracts: ['RawTickStreamContract', 'ExchangeStatusContract'],
    outputContract: 'IntegrityStatusContract',
    featureDependencies: ['bid_ask_spread', 'sequence_continuity', 'timestamp_jitter'],
    providerDependencies: ['binance', 'kraken', 'coinbase', 'twelvedata'],
    calculationVersion: '1.2.0',
    refreshPolicy: { frequency: 'tick_realtime', maxStalenessSeconds: 5, timeoutMs: 500 },
    weightPolicy: { defaultWeight: 1.0, isEligibleGate: true, isVetoOverride: true },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.95, confidenceDecayHalfLifeHours: 0.1 },
    riskPolicy: { penaltyCeiling: 100, blocksActionableRank: true },
    reasonCodeCatalog: [
      { code: 'MIG_CROSSED_BOOK', descriptionDe: 'Bid über Ask erkannt; ungültiges Orderbuch', severity: 'critical' },
      { code: 'MIG_SEQUENCE_GAP', descriptionDe: 'Lücke in Nachrichten-Sequenz der Börse', severity: 'warning' },
    ],
    owner: 'Market Data Ingestion Squad',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'data_quality_scorer',
    displayName: 'Data Quality Scorer',
    domain: 'data-quality',
    assetClassScope: ['crypto', 'equity_us', 'equity_eu', 'commodities', 'forex', 'indices'],
    status: 'active',
    provenanceMode: 'live',
    inputContracts: ['FeedLatencyMetricContract', 'TickGapContract'],
    outputContract: 'DataQualityScoreContract',
    featureDependencies: ['latency_jitter_ms', 'missing_ticks_ratio', 'provider_agreement_score'],
    providerDependencies: ['binance', 'kraken', 'twelvedata', 'alphavantage'],
    calculationVersion: '1.1.0',
    refreshPolicy: { frequency: 'sub_second_conflated', maxStalenessSeconds: 10, timeoutMs: 1000 },
    weightPolicy: { defaultWeight: 0.8, isEligibleGate: true, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.90, confidenceDecayHalfLifeHours: 0.5 },
    riskPolicy: { penaltyCeiling: 50, blocksActionableRank: true },
    reasonCodeCatalog: [
      { code: 'DQS_HIGH_JITTER', descriptionDe: 'Hohe Latenzschwankung über 120ms', severity: 'warning' },
      { code: 'DQS_LOW_CONSENSUS', descriptionDe: 'Provider-Preise weichen um >1.2% ab', severity: 'critical' },
    ],
    owner: 'Reliability Engineering',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'liquidity_eligibility_scorer',
    displayName: 'Liquidity Eligibility Scorer',
    domain: 'risk-controls',
    assetClassScope: ['crypto', 'equity_us', 'equity_eu', 'commodities', 'forex'],
    status: 'active',
    provenanceMode: 'cached',
    inputContracts: ['OrderbookDepthContract', 'DailyTurnoverContract'],
    outputContract: 'LiquidityEligibilityContract',
    featureDependencies: ['turnover_24h_eur', 'orderbook_depth_2pct_eur', 'median_trade_size'],
    providerDependencies: ['binance', 'kraken', 'twelvedata'],
    calculationVersion: '1.0.0',
    refreshPolicy: { frequency: 'five_minutes', maxStalenessSeconds: 300, timeoutMs: 2000 },
    weightPolicy: { defaultWeight: 0.9, isEligibleGate: true, isVetoOverride: true },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.85, confidenceDecayHalfLifeHours: 2.0 },
    riskPolicy: { penaltyCeiling: 80, blocksActionableRank: true },
    reasonCodeCatalog: [
      { code: 'LES_ILLIQUID_UNDER_THRESHOLD', descriptionDe: '24h Handelsvolumen < 250.000 €; Asset nicht score-berechtigt', severity: 'critical' },
    ],
    owner: 'Execution Analytics',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'spread_slippage_risk_scorer',
    displayName: 'Spread & Slippage Risk Scorer',
    domain: 'risk-controls',
    assetClassScope: ['crypto', 'equity_us', 'equity_eu', 'forex'],
    status: 'active',
    provenanceMode: 'live',
    inputContracts: ['L1TopBookContract', 'TradeExecutionEstimateContract'],
    outputContract: 'SlippageRiskContract',
    featureDependencies: ['effective_spread_bps', 'modeled_market_impact_50k'],
    providerDependencies: ['binance', 'kraken'],
    calculationVersion: '1.0.0',
    refreshPolicy: { frequency: 'sub_second_conflated', maxStalenessSeconds: 15, timeoutMs: 800 },
    weightPolicy: { defaultWeight: 0.7, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.90, confidenceDecayHalfLifeHours: 0.2 },
    riskPolicy: { penaltyCeiling: 40, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'SSR_WIDE_SPREAD', descriptionDe: 'Spread > 35 Basispunkte; erhöhte Einstiegskosten', severity: 'warning' },
    ],
    owner: 'Execution Analytics',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'tradability_gate',
    displayName: 'Tradability Gate',
    domain: 'risk-controls',
    assetClassScope: ['crypto', 'equity_us', 'equity_eu', 'commodities', 'forex', 'indices', 'futures', 'bonds'],
    status: 'active',
    provenanceMode: 'live',
    inputContracts: ['MarketHaltContract', 'RegulatoryTradingStatusContract'],
    outputContract: 'TradabilityStatusContract',
    featureDependencies: ['exchange_trading_state', 'circuit_breaker_active'],
    providerDependencies: ['twelvedata', 'binance'],
    calculationVersion: '1.0.0',
    refreshPolicy: { frequency: 'one_minute', maxStalenessSeconds: 60, timeoutMs: 1000 },
    weightPolicy: { defaultWeight: 1.0, isEligibleGate: true, isVetoOverride: true },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.99, confidenceDecayHalfLifeHours: 0.1 },
    riskPolicy: { penaltyCeiling: 100, blocksActionableRank: true },
    reasonCodeCatalog: [
      { code: 'TBG_HALTED', descriptionDe: 'Handelsaussetzung oder Circuit Breaker aktiv', severity: 'critical' },
    ],
    owner: 'Compliance & Governance',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },

  // 6-15: Technical, Trend & Quantitative Price Dynamics
  {
    componentId: 'multi_timeframe_trend_regime_scorer',
    displayName: 'Multi-Timeframe Trend Regime Scorer',
    domain: 'scoring',
    assetClassScope: ['crypto', 'equity_us', 'equity_eu', 'indices', 'forex', 'commodities'],
    status: 'active',
    provenanceMode: 'cached',
    inputContracts: ['MultiTimeframeCandlesContract'],
    outputContract: 'TrendRegimeScoreContract',
    featureDependencies: ['ema_20_50_200_alignment', 'adx_14_strength', 'higher_highs_structure'],
    providerDependencies: ['binance', 'twelvedata'],
    calculationVersion: '2.0.0',
    refreshPolicy: { frequency: 'five_minutes', maxStalenessSeconds: 300, timeoutMs: 1500 },
    weightPolicy: { defaultWeight: 0.25, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.90, confidenceDecayHalfLifeHours: 4.0 },
    riskPolicy: { penaltyCeiling: 0, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'MTF_STRONG_BULL_REGIME', descriptionDe: 'Trendbestätigung über 15m, 1h und 1d', severity: 'info' },
    ],
    owner: 'Quant Strategy Team',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'relative_strength_scorer',
    displayName: 'Relative Strength Scorer',
    domain: 'scoring',
    assetClassScope: ['equity_us', 'equity_eu', 'crypto'],
    status: 'active',
    provenanceMode: 'cached',
    inputContracts: ['BenchmarkReturnContract', 'AssetReturnContract'],
    outputContract: 'RelativeStrengthScoreContract',
    featureDependencies: ['alpha_vs_sp500_60d', 'rs_percentile_rank_in_sector'],
    providerDependencies: ['twelvedata'],
    calculationVersion: '1.2.0',
    refreshPolicy: { frequency: 'hourly', maxStalenessSeconds: 3600, timeoutMs: 2000 },
    weightPolicy: { defaultWeight: 0.20, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.95, confidenceDecayHalfLifeHours: 12.0 },
    riskPolicy: { penaltyCeiling: 0, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'RS_SECTOR_OUTPERFORMER', descriptionDe: 'Relative Stärke im obersten Dezil der Peergroup', severity: 'info' },
    ],
    owner: 'Quant Strategy Team',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'momentum_persistence_scorer',
    displayName: 'Momentum Persistence Scorer',
    domain: 'scoring',
    assetClassScope: ['crypto', 'equity_us', 'equity_eu', 'indices'],
    status: 'active',
    provenanceMode: 'cached',
    inputContracts: ['HistoricalCandlesContract'],
    outputContract: 'MomentumPersistenceScoreContract',
    featureDependencies: ['rate_of_change_14d', 'hurst_exponent', 'positive_day_ratio_30d'],
    providerDependencies: ['binance', 'twelvedata'],
    calculationVersion: '1.1.0',
    refreshPolicy: { frequency: 'hourly', maxStalenessSeconds: 3600, timeoutMs: 2000 },
    weightPolicy: { defaultWeight: 0.15, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.90, confidenceDecayHalfLifeHours: 8.0 },
    riskPolicy: { penaltyCeiling: 0, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'MOM_SUSTAINED_ACCELERATION', descriptionDe: 'Konstante Momentum-Beschleunigung ohne Erschöpfungssignale', severity: 'info' },
    ],
    owner: 'Quant Strategy Team',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'breakout_quality_scorer',
    displayName: 'Breakout Quality Scorer',
    domain: 'scoring',
    assetClassScope: ['crypto', 'equity_us', 'equity_eu', 'commodities'],
    status: 'active',
    provenanceMode: 'live',
    inputContracts: ['RecentBreakoutContract', 'VolumeExpansionContract'],
    outputContract: 'BreakoutQualityScoreContract',
    featureDependencies: ['consolidation_range_duration_days', 'breakout_volume_multiple', 'close_above_resistance_pct'],
    providerDependencies: ['binance', 'twelvedata'],
    calculationVersion: '1.0.0',
    refreshPolicy: { frequency: 'five_minutes', maxStalenessSeconds: 300, timeoutMs: 1500 },
    weightPolicy: { defaultWeight: 0.15, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.85, confidenceDecayHalfLifeHours: 2.0 },
    riskPolicy: { penaltyCeiling: 0, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'BRK_CLEAN_RESISTANCE_CLEARANCE', descriptionDe: 'Sauberer Ausbruch mit >2.5x durchschnittlichem Volumen', severity: 'info' },
    ],
    owner: 'Technical Analysis Squad',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'mean_reversion_opportunity_scorer',
    displayName: 'Mean Reversion Opportunity Scorer',
    domain: 'scoring',
    assetClassScope: ['crypto', 'equity_us', 'indices', 'forex'],
    status: 'active',
    provenanceMode: 'live',
    inputContracts: ['OscillatorContract', 'BollingerBandContract'],
    outputContract: 'MeanReversionScoreContract',
    featureDependencies: ['rsi_14_oversold', 'z_score_vs_20d_sma', 'bollinger_percent_b'],
    providerDependencies: ['binance', 'twelvedata'],
    calculationVersion: '1.0.0',
    refreshPolicy: { frequency: 'five_minutes', maxStalenessSeconds: 300, timeoutMs: 1000 },
    weightPolicy: { defaultWeight: 0.10, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.90, confidenceDecayHalfLifeHours: 1.0 },
    riskPolicy: { penaltyCeiling: 0, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'MR_EXTREME_STRETCH', descriptionDe: 'Statistische Überdehnung (-2.8 Sigma); Rückkehr zum Mittelwert wahrscheinlich', severity: 'info' },
    ],
    owner: 'Technical Analysis Squad',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'volume_confirmation_scorer',
    displayName: 'Volume Confirmation Scorer',
    domain: 'scoring',
    assetClassScope: ['crypto', 'equity_us', 'equity_eu'],
    status: 'active',
    provenanceMode: 'live',
    inputContracts: ['IntradayVolumeContract', 'HistoricalAverageVolumeContract'],
    outputContract: 'VolumeConfirmationScoreContract',
    featureDependencies: ['obv_trend_direction', 'volume_profile_poc_proximity', 'rvol_intraday'],
    providerDependencies: ['binance', 'twelvedata'],
    calculationVersion: '1.1.0',
    refreshPolicy: { frequency: 'one_minute', maxStalenessSeconds: 60, timeoutMs: 800 },
    weightPolicy: { defaultWeight: 0.15, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.90, confidenceDecayHalfLifeHours: 1.0 },
    riskPolicy: { penaltyCeiling: 25, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'VOL_DIVERGENCE_WARNING', descriptionDe: 'Preisanstieg bei abnehmendem Volumen; geringe Trendbestätigung', severity: 'warning' },
    ],
    owner: 'Technical Analysis Squad',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'volatility_regime_scorer',
    displayName: 'Volatility Regime Scorer',
    domain: 'risk-controls',
    assetClassScope: ['crypto', 'equity_us', 'indices', 'forex', 'commodities'],
    status: 'active',
    provenanceMode: 'cached',
    inputContracts: ['ATRContract', 'HistoricalVolatilityContract'],
    outputContract: 'VolatilityRegimeScoreContract',
    featureDependencies: ['atr_14_percentile', 'parkinson_volatility', 'implied_vs_realized_ratio'],
    providerDependencies: ['twelvedata', 'binance'],
    calculationVersion: '1.0.0',
    refreshPolicy: { frequency: 'five_minutes', maxStalenessSeconds: 300, timeoutMs: 1000 },
    weightPolicy: { defaultWeight: 0.10, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.90, confidenceDecayHalfLifeHours: 6.0 },
    riskPolicy: { penaltyCeiling: 30, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'VOL_COMPRESSION_SQUEEZE', descriptionDe: 'Extreme Volatilitätskompression; dynamische Ausbruchsbewegung bevorstehend', severity: 'info' },
    ],
    owner: 'Risk Analytics',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'support_resistance_proximity_scorer',
    displayName: 'Support/Resistance Proximity Scorer',
    domain: 'scoring',
    assetClassScope: ['crypto', 'equity_us', 'equity_eu', 'indices'],
    status: 'active',
    provenanceMode: 'cached',
    inputContracts: ['KeyLevelsContract', 'CurrentPriceContract'],
    outputContract: 'KeyLevelProximityScoreContract',
    featureDependencies: ['distance_to_major_support_pct', 'distance_to_major_resistance_pct', 'level_touch_count'],
    providerDependencies: ['binance', 'twelvedata'],
    calculationVersion: '1.0.0',
    refreshPolicy: { frequency: 'five_minutes', maxStalenessSeconds: 300, timeoutMs: 1200 },
    weightPolicy: { defaultWeight: 0.10, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.85, confidenceDecayHalfLifeHours: 12.0 },
    riskPolicy: { penaltyCeiling: 0, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'SR_TESTING_KEY_SUPPORT', descriptionDe: 'Kurs testet signifikanten 3-fach bestätigten Unterstützungsbereich', severity: 'info' },
    ],
    owner: 'Technical Analysis Squad',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'pattern_confidence_scorer',
    displayName: 'Pattern Confidence Scorer',
    domain: 'scoring',
    assetClassScope: ['crypto', 'equity_us', 'indices'],
    status: 'active',
    provenanceMode: 'cached',
    inputContracts: ['ChartPatternDetectionContract'],
    outputContract: 'PatternConfidenceScoreContract',
    featureDependencies: ['pattern_geometry_symmetry', 'completion_ratio', 'historical_win_rate_in_regime'],
    providerDependencies: ['twelvedata'],
    calculationVersion: '1.0.0',
    refreshPolicy: { frequency: 'hourly', maxStalenessSeconds: 3600, timeoutMs: 2500 },
    weightPolicy: { defaultWeight: 0.10, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.80, confidenceDecayHalfLifeHours: 8.0 },
    riskPolicy: { penaltyCeiling: 0, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'PAT_DOUBLE_BOTTOM_CONFIRMED', descriptionDe: 'Bestätigte Doppelboden-Formation mit Nackenlinien-Bruch', severity: 'info' },
    ],
    owner: 'AI Pattern Recognition Squad',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'vwap_location_scorer',
    displayName: 'VWAP Location Scorer',
    domain: 'scoring',
    assetClassScope: ['crypto', 'equity_us', 'futures'],
    status: 'active',
    provenanceMode: 'live',
    inputContracts: ['IntradayTickVolumeContract'],
    outputContract: 'VWAPLocationScoreContract',
    featureDependencies: ['price_vs_session_vwap_pct', 'vwap_standard_deviation_band'],
    providerDependencies: ['binance', 'kraken'],
    calculationVersion: '1.1.0',
    refreshPolicy: { frequency: 'one_minute', maxStalenessSeconds: 60, timeoutMs: 500 },
    weightPolicy: { defaultWeight: 0.15, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.95, confidenceDecayHalfLifeHours: 0.5 },
    riskPolicy: { penaltyCeiling: 0, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'VWAP_BULL_ACCEPTANCE', descriptionDe: 'Kurs handelt stabil oberhalb des täglichen VWAP mit steigendem Volumen', severity: 'info' },
    ],
    owner: 'Execution Analytics',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },

  // 16-21: Macro, Breadth, Sector & Cross-Asset
  {
    componentId: 'market_breadth_scorer',
    displayName: 'Market Breadth Scorer',
    domain: 'market-intelligence',
    assetClassScope: ['equity_us', 'equity_eu', 'crypto'],
    status: 'active',
    provenanceMode: 'cached',
    inputContracts: ['ConstituentAdvanceDeclineContract'],
    outputContract: 'MarketBreadthScoreContract',
    featureDependencies: ['advance_decline_ratio', 'stocks_above_50d_sma_pct', 'new_highs_vs_lows'],
    providerDependencies: ['twelvedata'],
    calculationVersion: '1.0.0',
    refreshPolicy: { frequency: 'hourly', maxStalenessSeconds: 3600, timeoutMs: 3000 },
    weightPolicy: { defaultWeight: 0.15, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.90, confidenceDecayHalfLifeHours: 12.0 },
    riskPolicy: { penaltyCeiling: 20, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'BRD_STRONG_PARTICIPATION', descriptionDe: '>75% aller Index-Komponenten über ihrer 50-Tage-Linie', severity: 'info' },
    ],
    owner: 'Macro & Sector Research',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'sector_rotation_scorer',
    displayName: 'Sector Rotation Scorer',
    domain: 'market-intelligence',
    assetClassScope: ['equity_us', 'equity_eu'],
    status: 'active',
    provenanceMode: 'cached',
    inputContracts: ['SectorETFReturnsContract'],
    outputContract: 'SectorRotationScoreContract',
    featureDependencies: ['cyclical_vs_defensive_ratio', 'tech_vs_utilities_spread', 'sector_momentum_rank'],
    providerDependencies: ['twelvedata'],
    calculationVersion: '1.1.0',
    refreshPolicy: { frequency: 'daily_eod', maxStalenessSeconds: 86400, timeoutMs: 2000 },
    weightPolicy: { defaultWeight: 0.15, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.95, confidenceDecayHalfLifeHours: 24.0 },
    riskPolicy: { penaltyCeiling: 0, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'SEC_RISK_ON_EXPANSION', descriptionDe: 'Kapital rotiert in zyklische Wachstumswerte und Technologie', severity: 'info' },
    ],
    owner: 'Macro & Sector Research',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'correlation_diversification_scorer',
    displayName: 'Correlation & Diversification Scorer',
    domain: 'risk-controls',
    assetClassScope: ['crypto', 'equity_us', 'commodities', 'bonds'],
    status: 'active',
    provenanceMode: 'cached',
    inputContracts: ['CrossAssetCorrelationMatrixContract'],
    outputContract: 'CorrelationDiversificationScoreContract',
    featureDependencies: ['rolling_correlation_btc_sp500', 'gold_equity_decoupling_index'],
    providerDependencies: ['twelvedata', 'binance'],
    calculationVersion: '1.0.0',
    refreshPolicy: { frequency: 'daily_eod', maxStalenessSeconds: 86400, timeoutMs: 2500 },
    weightPolicy: { defaultWeight: 0.10, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.90, confidenceDecayHalfLifeHours: 24.0 },
    riskPolicy: { penaltyCeiling: 15, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'CORR_HIGH_SYSTEMIC_BOND', descriptionDe: 'Korrelation > 0.85; verringerte Diversifikationswirkung', severity: 'warning' },
    ],
    owner: 'Portfolio Risk Management',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'cross_asset_regime_scorer',
    displayName: 'Cross-Asset Regime Scorer',
    domain: 'market-intelligence',
    assetClassScope: ['indices', 'forex', 'commodities', 'bonds'],
    status: 'active',
    provenanceMode: 'cached',
    inputContracts: ['MacroYieldCurveContract', 'DXYContract', 'CommodityIndexContract'],
    outputContract: 'CrossAssetRegimeScoreContract',
    featureDependencies: ['us_10y_2y_yield_spread', 'dxy_strength_trend', 'crude_oil_momentum'],
    providerDependencies: ['fred', 'twelvedata'],
    calculationVersion: '1.0.0',
    refreshPolicy: { frequency: 'daily_eod', maxStalenessSeconds: 86400, timeoutMs: 3000 },
    weightPolicy: { defaultWeight: 0.15, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.95, confidenceDecayHalfLifeHours: 48.0 },
    riskPolicy: { penaltyCeiling: 0, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'CAR_INFLATIONARY_PRESSURE', descriptionDe: 'Rohstoffpreise steigen bei anziehenden Realzinsen', severity: 'warning' },
    ],
    owner: 'Macro Strategy Team',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'macro_surprise_scorer',
    displayName: 'Macro Surprise Scorer',
    domain: 'market-intelligence',
    assetClassScope: ['indices', 'forex', 'bonds', 'crypto'],
    status: 'active',
    provenanceMode: 'cached',
    inputContracts: ['EconomicReleaseVsConsensusContract'],
    outputContract: 'MacroSurpriseScoreContract',
    featureDependencies: ['cpi_surprise_delta', 'nfp_surprise_zscore', 'rate_decision_deviation'],
    providerDependencies: ['fred'],
    calculationVersion: '1.0.0',
    refreshPolicy: { frequency: 'on_event', maxStalenessSeconds: 86400, timeoutMs: 2000 },
    weightPolicy: { defaultWeight: 0.20, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.95, confidenceDecayHalfLifeHours: 12.0 },
    riskPolicy: { penaltyCeiling: 25, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'MAC_POSITIVE_GROWTH_SURPRISE', descriptionDe: 'Wirtschaftsdaten übertreffen Analystenkonsens deutlich', severity: 'info' },
    ],
    owner: 'Macro Strategy Team',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'economic_calendar_risk_scorer',
    displayName: 'Economic Calendar Risk Scorer',
    domain: 'risk-controls',
    assetClassScope: ['indices', 'forex', 'bonds', 'crypto', 'equity_us'],
    status: 'active',
    provenanceMode: 'cached',
    inputContracts: ['UpcomingEventsContract'],
    outputContract: 'EventRiskScoreContract',
    featureDependencies: ['hours_until_fomc_decision', 'tier1_event_clustering_index'],
    providerDependencies: ['fred'],
    calculationVersion: '1.0.0',
    refreshPolicy: { frequency: 'hourly', maxStalenessSeconds: 3600, timeoutMs: 1500 },
    weightPolicy: { defaultWeight: 0.10, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.95, confidenceDecayHalfLifeHours: 6.0 },
    riskPolicy: { penaltyCeiling: 45, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'ECR_HIGH_VOLATILITY_EVENT_IMMINENT', descriptionDe: 'FOMC Zinsentscheid in < 2 Stunden; erhöhtes Slippage-Risiko', severity: 'warning' },
    ],
    owner: 'Risk Analytics',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },

  // 22-32: News, NLP Sentiment, Events & Catalyst Engines
  {
    componentId: 'entity_resolution_engine',
    displayName: 'Entity Resolution Engine',
    domain: 'asset-master',
    assetClassScope: ['equity_us', 'equity_eu', 'crypto'],
    status: 'active',
    provenanceMode: 'cached',
    inputContracts: ['RawNewsHeadlineContract', 'SocialMentionContract'],
    outputContract: 'ResolvedEntityContract',
    featureDependencies: ['fuzzy_symbol_matching_confidence', 'isin_figi_lei_lookup'],
    providerDependencies: ['gemini', 'internal_master_data'],
    calculationVersion: '2.1.0',
    refreshPolicy: { frequency: 'tick_realtime', maxStalenessSeconds: 60, timeoutMs: 800 },
    weightPolicy: { defaultWeight: 1.0, isEligibleGate: true, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.92, confidenceDecayHalfLifeHours: 24.0 },
    riskPolicy: { penaltyCeiling: 50, blocksActionableRank: true },
    reasonCodeCatalog: [
      { code: 'ERE_AMBIGUOUS_TICKER', descriptionDe: 'Mehrdeutiges Symbol (z.B. BTC vs WBTC); manuelle Auflösung gefordert', severity: 'warning' },
    ],
    owner: 'Master Data & NLP Squad',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'news_relevance_scorer',
    displayName: 'News Relevance Scorer',
    domain: 'market-intelligence',
    assetClassScope: ['equity_us', 'equity_eu', 'crypto'],
    status: 'active',
    provenanceMode: 'live',
    inputContracts: ['NewsArticleBodyContract'],
    outputContract: 'NewsRelevanceScoreContract',
    featureDependencies: ['entity_mention_prominence', 'title_vs_body_salience', 'ticker_relevance_pct'],
    providerDependencies: ['gemini'],
    calculationVersion: '1.2.0',
    refreshPolicy: { frequency: 'five_minutes', maxStalenessSeconds: 300, timeoutMs: 1500 },
    weightPolicy: { defaultWeight: 0.20, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.85, confidenceDecayHalfLifeHours: 4.0 },
    riskPolicy: { penaltyCeiling: 0, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'NRS_PRIMARY_SUBJECT', descriptionDe: 'Asset ist das Hauptthema der Meldung (>80% Relevanz)', severity: 'info' },
    ],
    owner: 'NLP & AI Research',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'financial_sentiment_scorer',
    displayName: 'Financial Sentiment Scorer',
    domain: 'market-intelligence',
    assetClassScope: ['equity_us', 'equity_eu', 'crypto', 'indices'],
    status: 'active',
    provenanceMode: 'live',
    inputContracts: ['FilteredNewsStreamContract'],
    outputContract: 'FinancialSentimentScoreContract',
    featureDependencies: ['polarity_score_gemini', 'finbert_domain_sentiment', 'forward_looking_tone'],
    providerDependencies: ['gemini'],
    calculationVersion: '2.0.0',
    refreshPolicy: { frequency: 'five_minutes', maxStalenessSeconds: 300, timeoutMs: 2000 },
    weightPolicy: { defaultWeight: 0.20, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.80, confidenceDecayHalfLifeHours: 6.0 },
    riskPolicy: { penaltyCeiling: 0, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'FSS_STRONG_BULLISH_TONE', descriptionDe: 'Signifikant positive Tonalität in Finanzberichterstattung', severity: 'info' },
    ],
    owner: 'NLP & AI Research',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'sentiment_velocity_scorer',
    displayName: 'Sentiment Velocity Scorer',
    domain: 'market-intelligence',
    assetClassScope: ['crypto', 'equity_us'],
    status: 'active',
    provenanceMode: 'live',
    inputContracts: ['SentimentTimeSeriesContract'],
    outputContract: 'SentimentVelocityScoreContract',
    featureDependencies: ['sentiment_change_1h', 'sentiment_change_24h', 'velocity_acceleration'],
    providerDependencies: ['gemini'],
    calculationVersion: '1.0.0',
    refreshPolicy: { frequency: 'five_minutes', maxStalenessSeconds: 300, timeoutMs: 1500 },
    weightPolicy: { defaultWeight: 0.15, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.80, confidenceDecayHalfLifeHours: 2.0 },
    riskPolicy: { penaltyCeiling: 0, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'SV_SUDDEN_BULL_SURGE', descriptionDe: 'Sentiment dreht innerhalb von 60 Minuten von neutral auf stark positiv', severity: 'info' },
    ],
    owner: 'NLP & AI Research',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'sentiment_dispersion_scorer',
    displayName: 'Sentiment Dispersion Scorer',
    domain: 'risk-controls',
    assetClassScope: ['crypto', 'equity_us'],
    status: 'active',
    provenanceMode: 'cached',
    inputContracts: ['MultiSourceSentimentContract'],
    outputContract: 'SentimentDispersionScoreContract',
    featureDependencies: ['source_sentiment_variance', 'retail_vs_institutional_divergence'],
    providerDependencies: ['gemini'],
    calculationVersion: '1.0.0',
    refreshPolicy: { frequency: 'hourly', maxStalenessSeconds: 3600, timeoutMs: 2000 },
    weightPolicy: { defaultWeight: 0.10, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.75, confidenceDecayHalfLifeHours: 8.0 },
    riskPolicy: { penaltyCeiling: 20, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'SD_HIGH_DISAGREEMENT', descriptionDe: 'Starke Meinungsspaltung zwischen Analysten und Social Media', severity: 'warning' },
    ],
    owner: 'NLP & AI Research',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'news_novelty_scorer',
    displayName: 'News Novelty Scorer',
    domain: 'market-intelligence',
    assetClassScope: ['equity_us', 'equity_eu', 'crypto'],
    status: 'active',
    provenanceMode: 'live',
    inputContracts: ['ArticleEmbeddingContract', 'HistoricalNewsStoreContract'],
    outputContract: 'NewsNoveltyScoreContract',
    featureDependencies: ['cosine_distance_to_historical_clusters', 'is_breaking_news'],
    providerDependencies: ['gemini'],
    calculationVersion: '1.1.0',
    refreshPolicy: { frequency: 'five_minutes', maxStalenessSeconds: 300, timeoutMs: 1800 },
    weightPolicy: { defaultWeight: 0.15, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.85, confidenceDecayHalfLifeHours: 3.0 },
    riskPolicy: { penaltyCeiling: 0, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'NN_NEW_FACTUAL_DEVELOPMENT', descriptionDe: 'Neues, zuvor unbekanntes Ereignis detektiert (keine Wiederholung)', severity: 'info' },
    ],
    owner: 'NLP & AI Research',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'source_authority_scorer',
    displayName: 'Source Authority Scorer',
    domain: 'data-quality',
    assetClassScope: ['equity_us', 'equity_eu', 'crypto'],
    status: 'active',
    provenanceMode: 'cached',
    inputContracts: ['PublisherDomainContract'],
    outputContract: 'SourceAuthorityScoreContract',
    featureDependencies: ['domain_reputation_tier', 'historical_accuracy_rating', 'sec_filing_flag'],
    providerDependencies: ['internal_master_data'],
    calculationVersion: '1.0.0',
    refreshPolicy: { frequency: 'daily_eod', maxStalenessSeconds: 86400, timeoutMs: 500 },
    weightPolicy: { defaultWeight: 0.20, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.95, confidenceDecayHalfLifeHours: 720.0 },
    riskPolicy: { penaltyCeiling: 30, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'SAS_TIER1_REGULATORY_SOURCE', descriptionDe: 'Quelle ist eine behördliche Einreichung (SEC/BaFin) mit höchster Autorität', severity: 'info' },
    ],
    owner: 'Compliance & Governance',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'event_detection_classification_engine',
    displayName: 'Event Detection & Classification Engine',
    domain: 'market-intelligence',
    assetClassScope: ['equity_us', 'equity_eu', 'crypto'],
    status: 'active',
    provenanceMode: 'live',
    inputContracts: ['StructuredNewsEventContract'],
    outputContract: 'ClassifiedEventContract',
    featureDependencies: ['event_type_taxonomy', 'merger_acquisition_flag', 'lawsuit_penalty_flag'],
    providerDependencies: ['gemini'],
    calculationVersion: '1.3.0',
    refreshPolicy: { frequency: 'five_minutes', maxStalenessSeconds: 300, timeoutMs: 2200 },
    weightPolicy: { defaultWeight: 0.25, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.88, confidenceDecayHalfLifeHours: 6.0 },
    riskPolicy: { penaltyCeiling: 0, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'EDE_EARNINGS_ANNOUNCEMENT', descriptionDe: 'Quartalszahlen offiziell publiziert', severity: 'info' },
    ],
    owner: 'NLP & AI Research',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'event_impact_scorer',
    displayName: 'Event Impact Scorer',
    domain: 'scoring',
    assetClassScope: ['equity_us', 'equity_eu', 'crypto'],
    status: 'active',
    provenanceMode: 'live',
    inputContracts: ['ClassifiedEventContract', 'MarketCapContract'],
    outputContract: 'EventImpactScoreContract',
    featureDependencies: ['estimated_ebitda_impact_pct', 'regulatory_threat_level'],
    providerDependencies: ['gemini'],
    calculationVersion: '1.1.0',
    refreshPolicy: { frequency: 'five_minutes', maxStalenessSeconds: 300, timeoutMs: 2000 },
    weightPolicy: { defaultWeight: 0.20, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.82, confidenceDecayHalfLifeHours: 12.0 },
    riskPolicy: { penaltyCeiling: 50, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'EIS_MATERIAL_FINANCIAL_IMPACT', descriptionDe: 'Signifikanter Einfluss auf den Unternehmensgewinn erwartet', severity: 'info' },
    ],
    owner: 'Quant Strategy Team',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'catalyst_strength_scorer',
    displayName: 'Catalyst Strength Scorer',
    domain: 'scoring',
    assetClassScope: ['equity_us', 'equity_eu', 'crypto'],
    status: 'active',
    provenanceMode: 'cached',
    inputContracts: ['UpcomingCatalystCalendarContract'],
    outputContract: 'CatalystStrengthScoreContract',
    featureDependencies: ['days_to_catalyst', 'historical_catalyst_volatility_move'],
    providerDependencies: ['internal_master_data'],
    calculationVersion: '1.0.0',
    refreshPolicy: { frequency: 'hourly', maxStalenessSeconds: 3600, timeoutMs: 1500 },
    weightPolicy: { defaultWeight: 0.15, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.85, confidenceDecayHalfLifeHours: 24.0 },
    riskPolicy: { penaltyCeiling: 0, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'CAT_MAJOR_PRODUCT_LAUNCH', descriptionDe: 'Großes Produkt-Release oder FDA-Entscheid in Kürze', severity: 'info' },
    ],
    owner: 'Fundamental Research Squad',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'market_reaction_validator',
    displayName: 'Market Reaction Validator',
    domain: 'data-quality',
    assetClassScope: ['equity_us', 'equity_eu', 'crypto'],
    status: 'active',
    provenanceMode: 'live',
    inputContracts: ['ClassifiedEventContract', 'PostEventTickWindowContract'],
    outputContract: 'MarketReactionValidationContract',
    featureDependencies: ['initial_reaction_direction', 'reversal_in_15m_flag', 'abnormal_trading_volume'],
    providerDependencies: ['binance', 'twelvedata'],
    calculationVersion: '1.0.0',
    refreshPolicy: { frequency: 'one_minute', maxStalenessSeconds: 60, timeoutMs: 800 },
    weightPolicy: { defaultWeight: 0.15, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.90, confidenceDecayHalfLifeHours: 1.0 },
    riskPolicy: { penaltyCeiling: 30, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'MRV_SELL_THE_NEWS_CONFIRMED', descriptionDe: 'Klassische "Sell the News" Reaktion nach positiver Veröffentlichung', severity: 'warning' },
    ],
    owner: 'Execution Analytics',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },

  // 33-37: Social Attention & Manipulation Risk
  {
    componentId: 'narrative_emergence_scorer',
    displayName: 'Narrative Emergence Scorer',
    domain: 'market-intelligence',
    assetClassScope: ['crypto', 'equity_us'],
    status: 'active',
    provenanceMode: 'cached',
    inputContracts: ['TopicClusteringStreamContract'],
    outputContract: 'NarrativeEmergenceScoreContract',
    featureDependencies: ['new_topic_growth_rate_48h', 'cross_channel_adoption_rate'],
    providerDependencies: ['gemini'],
    calculationVersion: '1.0.0',
    refreshPolicy: { frequency: 'hourly', maxStalenessSeconds: 3600, timeoutMs: 3000 },
    weightPolicy: { defaultWeight: 0.15, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.80, confidenceDecayHalfLifeHours: 12.0 },
    riskPolicy: { penaltyCeiling: 0, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'NE_EARLY_STAGE_NARRATIVE', descriptionDe: 'Neues Branchenthema (z.B. DePIN, Robotik) gewinnt rasch an Verbreitung', severity: 'info' },
    ],
    owner: 'NLP & AI Research',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'narrative_saturation_scorer',
    displayName: 'Narrative Saturation Scorer',
    domain: 'risk-controls',
    assetClassScope: ['crypto', 'equity_us'],
    status: 'active',
    provenanceMode: 'cached',
    inputContracts: ['TopicFrequencyContract'],
    outputContract: 'NarrativeSaturationScoreContract',
    featureDependencies: ['mainstream_media_saturation_index', 'search_trend_exhaustion'],
    providerDependencies: ['gemini'],
    calculationVersion: '1.0.0',
    refreshPolicy: { frequency: 'hourly', maxStalenessSeconds: 3600, timeoutMs: 2500 },
    weightPolicy: { defaultWeight: 0.10, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.80, confidenceDecayHalfLifeHours: 24.0 },
    riskPolicy: { penaltyCeiling: 30, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'NS_MAXIMUM_HYPE_REACHED', descriptionDe: 'Narrativ ist übersättigt; erhöhtes Risiko einer Sentiment-Erschöpfung', severity: 'warning' },
    ],
    owner: 'NLP & AI Research',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'social_attention_velocity_scorer',
    displayName: 'Social Attention Velocity Scorer',
    domain: 'market-intelligence',
    assetClassScope: ['crypto', 'equity_us'],
    status: 'active',
    provenanceMode: 'cached',
    inputContracts: ['SocialMentionVolumeContract'],
    outputContract: 'SocialAttentionVelocityScoreContract',
    featureDependencies: ['mention_zscore_vs_30d', 'retweet_spread_velocity'],
    providerDependencies: ['internal_master_data'],
    calculationVersion: '1.0.0',
    refreshPolicy: { frequency: 'five_minutes', maxStalenessSeconds: 300, timeoutMs: 1500 },
    weightPolicy: { defaultWeight: 0.10, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.75, confidenceDecayHalfLifeHours: 4.0 },
    riskPolicy: { penaltyCeiling: 0, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'SAV_VIRAL_ATTENTION_SURGE', descriptionDe: 'Erwähnungsrate übersteigt 3 Standardabweichungen des Normalwerts', severity: 'info' },
    ],
    owner: 'Social Intelligence Squad',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'social_engagement_quality_scorer',
    displayName: 'Social Engagement Quality Scorer',
    domain: 'data-quality',
    assetClassScope: ['crypto', 'equity_us'],
    status: 'active',
    provenanceMode: 'cached',
    inputContracts: ['SocialAuthorProfilesContract'],
    outputContract: 'SocialEngagementQualityScoreContract',
    featureDependencies: ['account_age_distribution', 'follower_to_following_ratio', 'verified_author_ratio'],
    providerDependencies: ['internal_master_data'],
    calculationVersion: '1.0.0',
    refreshPolicy: { frequency: 'hourly', maxStalenessSeconds: 3600, timeoutMs: 2000 },
    weightPolicy: { defaultWeight: 0.10, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.75, confidenceDecayHalfLifeHours: 12.0 },
    riskPolicy: { penaltyCeiling: 25, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'SEQ_ORGANIC_COMMUNITY_ENGAGEMENT', descriptionDe: 'Diskussion wird von etablierten Branchen-Accounts getragen', severity: 'info' },
    ],
    owner: 'Social Intelligence Squad',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'bot_manipulation_risk_scorer',
    displayName: 'Bot & Manipulation Risk Scorer',
    domain: 'risk-controls',
    assetClassScope: ['crypto', 'equity_us'],
    status: 'active',
    provenanceMode: 'live',
    inputContracts: ['SocialTimeFrequencyContract', 'OrderbookSpoofingContract'],
    outputContract: 'ManipulationRiskScoreContract',
    featureDependencies: ['sybil_attack_probability', 'pump_and_dump_pattern_similarity'],
    providerDependencies: ['internal_master_data', 'gemini'],
    calculationVersion: '1.2.0',
    refreshPolicy: { frequency: 'five_minutes', maxStalenessSeconds: 300, timeoutMs: 2000 },
    weightPolicy: { defaultWeight: 0.15, isEligibleGate: true, isVetoOverride: true },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.85, confidenceDecayHalfLifeHours: 2.0 },
    riskPolicy: { penaltyCeiling: 80, blocksActionableRank: true },
    reasonCodeCatalog: [
      { code: 'BMR_COORDINATED_ASTROTURFING', descriptionDe: 'Künstlich erzeugter Hype durch koordiniertes Bot-Netzwerk', severity: 'critical' },
    ],
    owner: 'Integrity & Security Squad',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },

  // 38-43: Fundamentals, Valuation & Financial Health
  {
    componentId: 'fundamental_quality_scorer',
    displayName: 'Fundamental Quality Scorer',
    domain: 'scoring',
    assetClassScope: ['equity_us', 'equity_eu'],
    status: 'active',
    provenanceMode: 'cached',
    inputContracts: ['SEC10K10QFinancialsContract'],
    outputContract: 'FundamentalQualityScoreContract',
    featureDependencies: ['piotroski_f_score', 'return_on_equity_10y_median', 'free_cash_flow_margin'],
    providerDependencies: ['sec_edgar', 'financialmodelingprep'],
    calculationVersion: '2.0.0',
    refreshPolicy: { frequency: 'daily_eod', maxStalenessSeconds: 86400, timeoutMs: 2500 },
    weightPolicy: { defaultWeight: 0.35, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.95, confidenceDecayHalfLifeHours: 2160.0 },
    riskPolicy: { penaltyCeiling: 0, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'FQS_HIGH_MOAT_QUALITY', descriptionDe: 'Exzellente Bilanzqualität (F-Score >= 8) mit beständigem Free Cash Flow', severity: 'info' },
    ],
    owner: 'Fundamental Research Squad',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'growth_acceleration_scorer',
    displayName: 'Growth Acceleration Scorer',
    domain: 'scoring',
    assetClassScope: ['equity_us', 'equity_eu'],
    status: 'active',
    provenanceMode: 'cached',
    inputContracts: ['QuarterlyFinancialsSeriesContract'],
    outputContract: 'GrowthAccelerationScoreContract',
    featureDependencies: ['revenue_growth_yoy_sequential_delta', 'eps_growth_3y_cagr'],
    providerDependencies: ['sec_edgar', 'financialmodelingprep'],
    calculationVersion: '1.1.0',
    refreshPolicy: { frequency: 'daily_eod', maxStalenessSeconds: 86400, timeoutMs: 2500 },
    weightPolicy: { defaultWeight: 0.25, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.95, confidenceDecayHalfLifeHours: 2160.0 },
    riskPolicy: { penaltyCeiling: 0, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'GAS_ACCELERATING_REVENUE', descriptionDe: 'Umsatzwachstum beschleunigt sich über 3 aufeinanderfolgende Quartale', severity: 'info' },
    ],
    owner: 'Fundamental Research Squad',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'valuation_peer_comparison_scorer',
    displayName: 'Valuation & Peer Comparison Scorer',
    domain: 'scoring',
    assetClassScope: ['equity_us', 'equity_eu'],
    status: 'active',
    provenanceMode: 'cached',
    inputContracts: ['CompanyMultiplesContract', 'SectorPeersMultiplesContract'],
    outputContract: 'ValuationScoreContract',
    featureDependencies: ['pe_ratio_vs_sector_median', 'ev_to_ebitda_percentile', 'peg_ratio'],
    providerDependencies: ['financialmodelingprep'],
    calculationVersion: '1.2.0',
    refreshPolicy: { frequency: 'daily_eod', maxStalenessSeconds: 86400, timeoutMs: 2000 },
    weightPolicy: { defaultWeight: 0.25, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.92, confidenceDecayHalfLifeHours: 720.0 },
    riskPolicy: { penaltyCeiling: 0, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'VAL_DISCOUNT_TO_PEERS', descriptionDe: 'Attraktive Bewertung mit >20% Abschlag zum Branchenmedian bei gleicher Marge', severity: 'info' },
    ],
    owner: 'Fundamental Research Squad',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'earnings_revision_scorer',
    displayName: 'Earnings Revision Scorer',
    domain: 'scoring',
    assetClassScope: ['equity_us', 'equity_eu'],
    status: 'active',
    provenanceMode: 'cached',
    inputContracts: ['ConsensusEstimatesContract'],
    outputContract: 'EarningsRevisionScoreContract',
    featureDependencies: ['eps_estimate_upward_revisions_30d', 'revenue_revision_diffusion_index'],
    providerDependencies: ['financialmodelingprep'],
    calculationVersion: '1.0.0',
    refreshPolicy: { frequency: 'daily_eod', maxStalenessSeconds: 86400, timeoutMs: 2000 },
    weightPolicy: { defaultWeight: 0.20, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.90, confidenceDecayHalfLifeHours: 360.0 },
    riskPolicy: { penaltyCeiling: 0, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'ER_ANALYST_UPGRADE_CYCLE', descriptionDe: '>70% der Analysten haben ihre Gewinnprognosen im letzten Monat angehoben', severity: 'info' },
    ],
    owner: 'Fundamental Research Squad',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'earnings_surprise_guidance_scorer',
    displayName: 'Earnings Surprise & Guidance Scorer',
    domain: 'scoring',
    assetClassScope: ['equity_us', 'equity_eu'],
    status: 'active',
    provenanceMode: 'cached',
    inputContracts: ['EarningsHistoryContract'],
    outputContract: 'EarningsSurpriseScoreContract',
    featureDependencies: ['last_earnings_surprise_pct', 'forward_guidance_raised_flag'],
    providerDependencies: ['financialmodelingprep', 'sec_edgar'],
    calculationVersion: '1.0.0',
    refreshPolicy: { frequency: 'daily_eod', maxStalenessSeconds: 86400, timeoutMs: 2000 },
    weightPolicy: { defaultWeight: 0.20, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.90, confidenceDecayHalfLifeHours: 720.0 },
    riskPolicy: { penaltyCeiling: 0, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'ESG_DOUBLE_BEAT_RAISE', descriptionDe: 'Umsatz und Gewinn übertroffen; Jahresprognose nach oben angepasst', severity: 'info' },
    ],
    owner: 'Fundamental Research Squad',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'financial_distress_scorer',
    displayName: 'Financial Distress Scorer',
    domain: 'risk-controls',
    assetClassScope: ['equity_us', 'equity_eu'],
    status: 'active',
    provenanceMode: 'cached',
    inputContracts: ['BalanceSheetDebtContract'],
    outputContract: 'FinancialDistressScoreContract',
    featureDependencies: ['altman_z_score', 'interest_coverage_ratio', 'debt_to_equity'],
    providerDependencies: ['sec_edgar', 'financialmodelingprep'],
    calculationVersion: '1.1.0',
    refreshPolicy: { frequency: 'daily_eod', maxStalenessSeconds: 86400, timeoutMs: 1500 },
    weightPolicy: { defaultWeight: 0.25, isEligibleGate: true, isVetoOverride: true },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.95, confidenceDecayHalfLifeHours: 2160.0 },
    riskPolicy: { penaltyCeiling: 100, blocksActionableRank: true },
    reasonCodeCatalog: [
      { code: 'FDS_INSOLVENCY_ZONE', descriptionDe: 'Altman Z-Score < 1.8; akutes Insolvenz- und Refinanzierungsrisiko', severity: 'critical' },
    ],
    owner: 'Risk Analytics',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },

  // 44-49: Smart Money, Positioning, Orderflow & On-Chain
  {
    componentId: 'insider_institutional_flow_scorer',
    displayName: 'Insider & Institutional Flow Scorer',
    domain: 'market-intelligence',
    assetClassScope: ['equity_us'],
    status: 'active',
    provenanceMode: 'cached',
    inputContracts: ['SECForm4Contract', 'SEC13FHoldingsContract'],
    outputContract: 'InsiderInstitutionalFlowScoreContract',
    featureDependencies: ['insider_net_buying_ratio_90d', 'institutional_ownership_change_qoq'],
    providerDependencies: ['sec_edgar'],
    calculationVersion: '1.1.0',
    refreshPolicy: { frequency: 'daily_eod', maxStalenessSeconds: 86400, timeoutMs: 3000 },
    weightPolicy: { defaultWeight: 0.20, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.88, confidenceDecayHalfLifeHours: 720.0 },
    riskPolicy: { penaltyCeiling: 0, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'IIF_CLUSTER_INSIDER_BUYING', descriptionDe: 'Mehrere Vorstände und Aufsichtsräte kaufen zeitgleich Aktien im offenen Markt', severity: 'info' },
    ],
    owner: 'Smart Money Research',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'options_positioning_gamma_scorer',
    displayName: 'Options Positioning & Gamma Scorer',
    domain: 'market-intelligence',
    assetClassScope: ['equity_us', 'indices'],
    status: 'active',
    provenanceMode: 'cached',
    inputContracts: ['OptionsChainContract'],
    outputContract: 'GammaPositioningScoreContract',
    featureDependencies: ['gamma_exposure_gex_regime', 'put_call_ratio_open_interest', 'max_pain_price_distance'],
    providerDependencies: ['twelvedata'],
    calculationVersion: '1.0.0',
    refreshPolicy: { frequency: 'hourly', maxStalenessSeconds: 3600, timeoutMs: 3500 },
    weightPolicy: { defaultWeight: 0.20, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.85, confidenceDecayHalfLifeHours: 8.0 },
    riskPolicy: { penaltyCeiling: 0, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'OPG_SHORT_GAMMA_VOLATILITY', descriptionDe: 'Market Maker im Short-Gamma-Bereich; Kursbewegungen werden dynamisch verstärkt', severity: 'info' },
    ],
    owner: 'Derivatives & Positioning Squad',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'open_interest_funding_regime_scorer',
    displayName: 'Open Interest & Funding Regime Scorer',
    domain: 'market-intelligence',
    assetClassScope: ['crypto'],
    status: 'active',
    provenanceMode: 'live',
    inputContracts: ['FuturesOpenInterestContract', 'PerpetualFundingRateContract'],
    outputContract: 'PerpetualMarketRegimeScoreContract',
    featureDependencies: ['funding_rate_annualized', 'oi_weighted_by_market_cap', 'liquidation_cascade_risk_score'],
    providerDependencies: ['binance', 'kraken'],
    calculationVersion: '1.2.0',
    refreshPolicy: { frequency: 'five_minutes', maxStalenessSeconds: 300, timeoutMs: 1500 },
    weightPolicy: { defaultWeight: 0.25, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.92, confidenceDecayHalfLifeHours: 4.0 },
    riskPolicy: { penaltyCeiling: 35, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'OIF_NEGATIVE_FUNDING_SHORT_SQUEEZE', descriptionDe: 'Stark negative Funding Rate bei hohem Open Interest; Short-Squeeze Setup', severity: 'info' },
    ],
    owner: 'Crypto Derivatives Squad',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'orderflow_liquidity_imbalance_scorer',
    displayName: 'Orderflow Liquidity Imbalance Scorer',
    domain: 'scoring',
    assetClassScope: ['crypto', 'equity_us', 'futures'],
    status: 'active',
    provenanceMode: 'live',
    inputContracts: ['L2OrderbookDeltaContract', 'AggregatedTradesContract'],
    outputContract: 'OrderflowImbalanceScoreContract',
    featureDependencies: ['cumulative_volume_delta_cvd', 'bid_ask_imbalance_ratio_l2', 'iceberg_order_detection_flag'],
    providerDependencies: ['binance', 'kraken'],
    calculationVersion: '1.3.0',
    refreshPolicy: { frequency: 'sub_second_conflated', maxStalenessSeconds: 10, timeoutMs: 800 },
    weightPolicy: { defaultWeight: 0.25, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.90, confidenceDecayHalfLifeHours: 0.25 },
    riskPolicy: { penaltyCeiling: 0, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'OLI_AGGRESSIVE_BUY_PRESSURE', descriptionDe: 'Signifikanter Anstieg des Cumulative Volume Delta (CVD) mit aggressiven Market-Käufen', severity: 'info' },
    ],
    owner: 'Execution Analytics',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'onchain_flow_holder_behavior_scorer',
    displayName: 'On-Chain Flow & Holder Behavior Scorer',
    domain: 'market-intelligence',
    assetClassScope: ['crypto'],
    status: 'active',
    provenanceMode: 'cached',
    inputContracts: ['OnChainWalletTransferContract', 'ExchangeReserveContract'],
    outputContract: 'OnChainHoldersScoreContract',
    featureDependencies: ['exchange_net_inflow_outflow_btc', 'long_term_holder_supply_pct', 'whale_wallet_accumulation_30d'],
    providerDependencies: ['binance', 'internal_master_data'],
    calculationVersion: '1.2.0',
    refreshPolicy: { frequency: 'hourly', maxStalenessSeconds: 3600, timeoutMs: 4000 },
    weightPolicy: { defaultWeight: 0.25, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.85, confidenceDecayHalfLifeHours: 24.0 },
    riskPolicy: { penaltyCeiling: 0, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'OCF_MASSIVE_COLD_STORAGE_OUTFLOW', descriptionDe: 'Große Bestände fließen von Börsen in Cold-Storage-Wallets ab', severity: 'info' },
    ],
    owner: 'Crypto Intelligence Squad',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
  {
    componentId: 'protocol_fundamentals_tokenomics_scorer',
    displayName: 'Protocol Fundamentals & Tokenomics Scorer',
    domain: 'scoring',
    assetClassScope: ['crypto'],
    status: 'active',
    provenanceMode: 'cached',
    inputContracts: ['DefiTvlFeesContract', 'TokenEmissionScheduleContract'],
    outputContract: 'TokenomicsScoreContract',
    featureDependencies: ['tvl_growth_30d', 'protocol_revenue_vs_market_cap', 'annual_token_inflation_rate'],
    providerDependencies: ['internal_master_data'],
    calculationVersion: '1.1.0',
    refreshPolicy: { frequency: 'daily_eod', maxStalenessSeconds: 86400, timeoutMs: 3000 },
    weightPolicy: { defaultWeight: 0.20, isEligibleGate: false, isVetoOverride: false },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.88, confidenceDecayHalfLifeHours: 168.0 },
    riskPolicy: { penaltyCeiling: 30, blocksActionableRank: false },
    reasonCodeCatalog: [
      { code: 'PFT_HIGH_FEE_GENERATION', descriptionDe: 'Protokoll generiert nachhaltige Gebühreneinnahmen im Verhältnis zur Marktkapitalisierung', severity: 'info' },
    ],
    owner: 'Crypto Intelligence Squad',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },

  // 50: Final Rank, Confidence & Evidence Synthesis Scorer
  {
    componentId: 'final_rank_confidence_evidence_scorer',
    displayName: 'Final Rank, Confidence & Evidence Scorer',
    domain: 'ranking',
    assetClassScope: ['crypto', 'equity_us', 'equity_eu', 'commodities', 'forex', 'indices', 'futures', 'bonds'],
    status: 'active',
    provenanceMode: 'live',
    inputContracts: ['CompositeScoresContract', 'EligibilityContract', 'EvidenceHashesContract'],
    outputContract: 'CanonicalActionableRankContract',
    featureDependencies: ['weighted_composite_score', 'total_evidence_sha256', 'aggregate_data_confidence'],
    providerDependencies: ['internal_consensus_engine'],
    calculationVersion: '3.0.0',
    refreshPolicy: { frequency: 'sub_second_conflated', maxStalenessSeconds: 15, timeoutMs: 1000 },
    weightPolicy: { defaultWeight: 1.0, isEligibleGate: true, isVetoOverride: true },
    confidencePolicy: { minimumDataSufficiencyRatio: 0.90, confidenceDecayHalfLifeHours: 0.25 },
    riskPolicy: { penaltyCeiling: 100, blocksActionableRank: true },
    reasonCodeCatalog: [
      { code: 'FRC_AUDIT_TRAIL_VERIFIED', descriptionDe: 'Vollständiger kryptographischer Fingerprint für BaFin/MiCA Audit-Trail erzeugt', severity: 'info' },
      { code: 'FRC_ACTIONABLE_RANK_BLOCKED', descriptionDe: 'Asset durch Risiko-Gate oder unzureichende Datenqualität gesperrt', severity: 'critical' },
    ],
    owner: 'Core Architecture & Ranking Squad',
    lastValidatedAt: '2026-09-28T00:00:00Z',
  },
];

// Helper functions for registry retrieval and validation
export function getAnalysisComponent(componentId: string): AnalysisComponentRegistryEntry | undefined {
  return CANONICAL_50_COMPONENTS.find((c) => c.componentId === componentId);
}

export function getComponentsByDomain(domain: CanonicalDomain): AnalysisComponentRegistryEntry[] {
  return CANONICAL_50_COMPONENTS.filter((c) => c.domain === domain);
}

export function getEligibleGateComponents(): AnalysisComponentRegistryEntry[] {
  return CANONICAL_50_COMPONENTS.filter((c) => c.weightPolicy.isEligibleGate);
}
