/**
 * CAPITAL AI — CANONICAL CONTRACTS & DTOS (PART 2 OF 3)
 * Defines core typed schemas for:
 * 1. AssetIdentity
 * 2. DataProvenance
 * 3. FeatureValue
 * 4. ScoreResult
 * 5. FinalRankResult
 */

import { z } from 'zod';
import { AssetClassSchema } from './common';

// =============================================================================
// 1. ASSET IDENTITY CONTRACT
// =============================================================================

export const AssetIdentitySchema = z.object({
  assetId: z.string().min(1),
  symbol: z.string().min(1),
  name: z.string().min(1),
  assetClass: AssetClassSchema,
  subclass: z.string().optional(),
  venue: z.string().min(1), // e.g. "BINANCE", "NASDAQ", "XETRA", "CME"
  currency: z.string().length(3), // ISO 4217, e.g. "EUR", "USD"
  status: z.enum(['active', 'halted', 'delisted', 'unverified']).default('active'),
  isin: z.string().optional(),
  figi: z.string().optional(),
  baseAsset: z.string().optional(),
  quoteAsset: z.string().optional(),
});
export type AssetIdentity = z.infer<typeof AssetIdentitySchema>;

// =============================================================================
// 2. DATA PROVENANCE CONTRACT
// =============================================================================

export const DataProvenanceSchema = z.object({
  providerId: z.string().min(1), // e.g. "binance_wss", "twelvedata_rest", "demo_seed"
  providerDataset: z.string().min(1), // e.g. "l1_top_book", "sec_10k_annual", "orderbook_l2"
  observedAt: z.number().int().positive(), // Epoch ms when generated by exchange
  receivedAt: z.number().int().positive(), // Epoch ms when received by Capital-AI gateway
  publishedAt: z.number().int().positive(), // Epoch ms when emitted to pipeline
  latencyMs: z.number().min(0), // Telemetry measured latency (receivedAt - observedAt)
  isDelayed: z.boolean(),
  isDemo: z.boolean(), // True if generated by explicit demo adapter; never false for seed data
  sourceReference: z.string().min(1), // Endpoint, socket channel or message ID
  licenseScope: z.enum([
    'public_realtime',
    'commercial_redistribution',
    'delayed_15m',
    'sandbox_demo',
    'academic_research',
  ]),
});
export type DataProvenance = z.infer<typeof DataProvenanceSchema>;

// =============================================================================
// 3. FEATURE VALUE CONTRACT
// =============================================================================

export const FeatureValueSchema = z.object({
  featureId: z.string().min(1), // e.g. "rsi_14", "f_score", "orderbook_imbalance_ratio"
  assetId: z.string().min(1),
  value: z.number(),
  unit: z.string().min(1), // e.g. "ratio", "percent", "eur", "usd", "bps", "index"
  normalizedValue: z.number().min(0).max(100), // Uniform 0-100 standard
  observedAt: z.number().int().positive(),
  calculationVersion: z.string().regex(/^\d+\.\d+\.\d+$/),
  qualityScore: z.number().min(0).max(100), // Data sufficiency for this feature
  provenance: DataProvenanceSchema,
});
export type FeatureValue = z.infer<typeof FeatureValueSchema>;

// =============================================================================
// 4. SCORE RESULT CONTRACT
// =============================================================================

export const ScoreResultSchema = z.object({
  componentId: z.string().min(1),
  assetId: z.string().min(1),
  score: z.number().min(0).max(100),
  scoreRange: z.object({
    min: z.number().default(0),
    max: z.number().default(100),
  }),
  confidence: z.number().min(0).max(1.0), // 0.0 to 1.0 reflecting completeness & freshness
  status: z.enum(['computed', 'insufficient_data', 'stale', 'blocked_by_risk', 'demo_fallback']),
  reasonCodes: z.array(z.string()),
  inputFeatureIds: z.array(z.string()),
  riskFlags: z.array(z.string()),
  calculationVersion: z.string().regex(/^\d+\.\d+\.\d+$/),
  computedAt: z.number().int().positive(),
  evidenceId: z.string().min(1), // SHA-256 reference
});
export type ScoreResult = z.infer<typeof ScoreResultSchema>;

// =============================================================================
// 5. FINAL RANK RESULT CONTRACT
// =============================================================================

export const DriverContributionSchema = z.object({
  componentId: z.string(),
  nameDe: z.string(),
  contributionScore: z.number(), // Points added/subtracted
  evidenceSummary: z.string(),
});
export type DriverContribution = z.infer<typeof DriverContributionSchema>;

export const FinalRankResultSchema = z.object({
  assetId: z.string().min(1),
  symbol: z.string().min(1),
  assetClass: AssetClassSchema,
  rank: z.number().int().positive().nullable(), // Nullable if eligibility is false
  finalScore: z.number().min(0).max(100),
  eligibility: z.boolean(), // Hard gate (0 = blocked, 1 = eligible)
  eligibilityReason: z.string().optional(),
  confidence: z.number().min(0).max(1.0),
  riskPenalty: z.number().min(0).max(100),
  subScores: z.object({
    momentumScore: z.number().min(0).max(100),
    technicalScore: z.number().min(0).max(100),
    fundamentalScore: z.number().min(0).max(100),
    sentimentScore: z.number().min(0).max(100),
    eventScore: z.number().min(0).max(100),
    positioningScore: z.number().min(0).max(100),
  }),
  weightsApplied: z.object({
    weightMomentum: z.number().min(0).max(1),
    weightTechnical: z.number().min(0).max(1),
    weightFundamental: z.number().min(0).max(1),
    weightSentiment: z.number().min(0).max(1),
    weightEvent: z.number().min(0).max(1),
    weightPositioning: z.number().min(0).max(1),
  }),
  topPositiveDrivers: z.array(DriverContributionSchema),
  topNegativeDrivers: z.array(DriverContributionSchema),
  reasonCodes: z.array(z.string()),
  modelVersion: z.string().regex(/^\d+\.\d+\.\d+$/),
  evidenceId: z.string().min(1),
  computedAt: z.number().int().positive(),
  isDemo: z.boolean(),
  regulatoryDisclaimer: z.string(),
});
export type FinalRankResult = z.infer<typeof FinalRankResultSchema>;
